import { NODE_FILTER_TYPE } from '../../graph/types';

export const WIDTH = 400;

export const NODE_FILTER_TYPES = [
  NODE_FILTER_TYPE.NO_FILTER,
  NODE_FILTER_TYPE.DEPENDENTS,
  NODE_FILTER_TYPE.DEPENENCIES,
  NODE_FILTER_TYPE.DEPENDENTS_AND_DEPENENCIES,
];
