
export enum NODE_TYPES {
    RESELECT_SELECTOR = 'RESELECT_SELECTOR',
    ASYNC_SELECTOR = 'ASYNC_SELECTOR',
    CONNECT = 'CONNECT',
    REACT_COMPONENT = 'REACT_COMPONENT',
    STATE_VARIABLE = 'STATE_VARIABLE',
    FUNCTION = 'FUNCTION',
}