"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var NODE_TYPES;
(function (NODE_TYPES) {
    NODE_TYPES["RESELECT_SELECTOR"] = "RESELECT_SELECTOR";
    NODE_TYPES["ASYNC_SELECTOR"] = "ASYNC_SELECTOR";
    NODE_TYPES["CONNECT"] = "CONNECT";
    NODE_TYPES["REACT_COMPONENT"] = "REACT_COMPONENT";
    NODE_TYPES["STATE_VARIABLE"] = "STATE_VARIABLE";
    NODE_TYPES["FUNCTION"] = "FUNCTION";
})(NODE_TYPES = exports.NODE_TYPES || (exports.NODE_TYPES = {}));
